subscribers:

  camera_reading:
    #topic: /camera/rgb/image_raw
    topic: /pupil/scene_with_gaze
    #topic: /hsrb/head_l_stereo_camera/image_raw
    
    queue_size: 1

actions:

  camera_reading:
    name: /pupil/darknet_ros/check_for_objects

publishers:

  object_detector:
    topic: /pupil/darknet_ros/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /pupil/darknet_ros/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /pupil/darknet_ros/detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true
